### ISSUE TITLE
Universal viewer not displaying image.

### ISSUE THREAD

**Issue by dswalker** [csuscholarworks/scholarworks#51]
Just shows an error.

https://scholarworks.calstate.edu/catalog?f%5Bresource_type_sim%5D%5B%5D=Photographic+Image&locale=en&q=&search_field=all_fields

**Comment by crisr15** [comment]
Has been a consistent problem since UV was put into place.  Was working for a hot second on the demo system but is not anymore.

**Comment by dswalker** [comment]
Fixed this issue by adding AllowEncodedSlashes On in Apache.
