### ISSUE TITLE
Some thumbnails for PDFs are inverted, wonky

### ISSUE THREAD

**Issue by dswalker** [csuscholarworks/scholarworks#52]
Some thumbnails for PDFs are color inverted:
https://scholarworks.calstate.edu/concern/theses/rj4309732

Other PDF thumbnails show as three small, repeated images of the first page:
https://scholarworks.calstate.edu/concern/theses/gh93h424v

**Comment by crisr15** [comment]
hyrax issue with investigation and feedback from other projects : https://github.com/samvera/hyrax/issues/4971

**Comment by dswalker** [comment]
fixed
